# Generated by Django 4.2.6 on 2023-11-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("cooking_time", models.PositiveIntegerField(help_text="in minutes")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("intermediate", "Intermediate"),
                        ],
                        default="easy",
                        max_length=12,
                    ),
                ),
                ("ingredients", models.ManyToManyField(to="ingredients.ingredient")),
            ],
        ),
    ]
